upstream academy_next {
    server 127.0.0.1:3000;
    keepalive 32;
}

server {
    server_name new.sepehrsarlakacademy.com
                server-76f17d5a-3a66-446f-9a66-e594e0324f34.ir-thr-fr1.arvancompute.ir
                185.239.104.230;

    client_max_body_size 20m;

    location /_next/static/ {
        alias /opt/sepehr-sarlak-academy/.next/static/;
        access_log off;
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    location / {
        proxy_pass http://academy_next;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;

    listen 443 ssl;
    listen [::]:443 ssl ipv6only=on;
    ssl_certificate /etc/letsencrypt/live/new.sepehrsarlakacademy.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/new.sepehrsarlakacademy.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}

server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name new.sepehrsarlakacademy.com
                server-76f17d5a-3a66-446f-9a66-e594e0324f34.ir-thr-fr1.arvancompute.ir
                185.239.104.230;

    return 301 https://new.sepehrsarlakacademy.com$request_uri;
}
